### ISSUE TITLE
V17 - Error al descargar txt de Retenciones SICORE Aplicadas

### ISSUE THREAD

**Issue by agusOrigami** [ingadhoc/odoo-argentina-ee#382]
Hola, 
Tenemos problemas al descargar el txt de SICORE (luego de liquidar las líneas de retenciones en pagos y publicar el asiento). Nos aparece este error:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/adhoc/odoo-argentina-ee/account_tax_settlement/models/account_move.py", line 22, in download_tax_settlement_file
    return self.settled_line_ids.get_tax_settlement_file(self.journal_id)
  File "/home/odoo/src/user/adhoc/odoo-argentina-ee/account_tax_settlement/models/account_move_line.py", line 138, in get_tax_settlement_file
    journal.get_tax_settlement_files_values(self))
  File "/home/odoo/src/user/adhoc/odoo-argentina-ee/account_tax_settlement/models/account_journal.py", line 312, in get_tax_settlement_files_values
    return getattr(
  File "/home/odoo/src/user/adhoc/odoo-argentina-ee/l10n_ar_account_tax_settlement/models/account_journal.py", line 1154, in sicore_aplicado_files_values
    amount_tot = abs(payment.l10n_ar_amount_total)
AttributeError: 'account.payment' object has no attribute 'l10n_ar_amount_total'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://origami-soft-cmsa-localizacion-ar-12847494.dev.odoo.com/web/assets/1e9b4be/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (https://origami-soft-cmsa-localizacion-ar-12847494.dev.odoo.com/web/assets/1e9b4be/web.assets_web.min.js:2874:13)

Desde ya, muchas gracias.

**Comment by agusOrigami** [comment]
@jjscarafia
