### ISSUE TITLE
No se puede bajar el archivo Sicore

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/odoo-argentina-ee#79]
Al intentar bajar el archivo sicore se produce el siguiente error, la prueba se hizo en runbot V15

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/ingadhoc/odoo-argentina-ee/account_tax_settlement/models/account_move_line.py", line 135, in get_tax_settlement_file
    journal.get_tax_settlement_files_values(self))
  File "/home/odoo/src/user/ingadhoc/odoo-argentina-ee/account_tax_settlement/models/account_journal.py", line 390, in get_tax_settlement_files_values
    return getattr(
  File "/home/odoo/src/user/ingadhoc/odoo-argentina-ee/l10n_ar_account_tax_settlement/models/account_journal.py", line 1172, in sicore_aplicado_files_values
    payment.payment_date).strftime('%d/%m/%Y')
AttributeError: 'account.payment' object has no attribute 'payment_date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1615, in run
    result = action.run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 639, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/addons/website/models/ir_actions.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 508, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'AttributeError'>: "'account.payment' object has no attribute 'payment_date'" while evaluating
'action = records.get_tax_settlement_file()'

**Comment by jjscarafia** [comment]
Buenas Jorge,
gracias por reportar. Entiendo que el bug debe ser en varios txt, te podrás hacer un PR cambiando payment_date por date (que cambió en account.payment), entiendo sería en todas estas:
* https://github.com/ingadhoc/odoo-argentina-ee/blob/15.0/l10n_ar_account_tax_settlement/models/account_journal.py#L1172
* https://github.com/ingadhoc/odoo-argentina-ee/blob/15.0/l10n_ar_account_tax_settlement/models/account_journal.py#L128
* https://github.com/ingadhoc/odoo-argentina-ee/blob/15.0/l10n_ar_account_tax_settlement/models/account_journal.py#L1188


En [este no](https://github.com/ingadhoc/odoo-argentina-ee/blob/15.0/l10n_ar_account_tax_settlement/models/account_journal.py#L1135) porque en payment group se sigue llamando igual


Al hacer el PR debería haber un runbot para volver a testear.

Gracias!

**Comment by jjscarafia** [comment]
@jobiols olvidé arrobarte arriba por las dudas.

gracias!

**Comment by jobiols** [comment]
@jjscarafia acabo de hacer el PR, supongo que hay que esperar para que aparezca en runbot..
o como lo veo?

**Comment by jjscarafia** [comment]
gracias! mezclado!
@jobiols
